imufile: "D:/Code/OB_GINS/dataset/car/Body-IMU/C1_imu_increments.txt"
gnssfile: "D:/Code/OB_GINS/dataset/car/Ground Truth/GINS_all.pos"
outputpath: "D:/Code/OB_GINS/dataset/car/out_car"
windows: 30
starttime: 353650
endtime: 356251
num_iterations: 20
is_outlier_culling: false
initvel: [0,0,0]
initatt: [0,0,276]
initgb: [0,0,0]
initab: [0,0,0]
imudatalen: 7
imudatarate: 200
isearth: true
antlever: [ -0.073, 0.302, 0.087 ]
odolever: [ -0.64, -0.628, 2.122 ]
bodyangle: [ 0, -0.30, -1.09 ]
odometer:
  isuseodo: false
  std: [0.05,0.05,0.05]
  srw: 100
  factor:
    use_nhc: false
imumodel:
  arw: 0.1
  vrw: 0.1
  gbstd: 25.0
  abstd: 200.0
  corrtime: 1.0
isuseoutage: false
outagetime: 0
outagelen: 0
outageperiod: 0
gnssthreshold: 0.2

odometer_left:
  isuseodo: true
  file: "D:/Code/OB_GINS/dataset/car/Odometer/odo_left_wimu_r.txt"
  columns: 2
  lever: [ -0.64, -0.628, 2.122 ]
  odoangle: [ 0, -0.30, -1.09 ]
  factor:
    sodo_prior_sigma: 0.02

odometer_right:
  isuseodo: true
  file: "D:/Code/OB_GINS/dataset/car/Odometer/odo_right.txt"
  columns: 2
  lever: [ -0.64, -0.628, 2.122 ]
  odoangle: [ 0, -0.30, -1.09 ]
  factor:
    sodo_prior_sigma: 0.02

odometer:
  isuseodo: false
  std: [0.05,0.05,0.05]
  srw: 100
  factor:
    use_nhc: true
    nhc_sigma: 0.1
    nhc_huber_delta: 0.5


wheel_imu_left:
  isuse: true
  file: "D:/Code/Wheel-INS/dataset/car/Wheel-IMU/C1_imu.bin"
  pick: norm   # norm|x|y|z
  radius: 0.3525
  lever: [ -0.64, -0.628, 2.122 ]
  odoangle: [ 0, -0.30, -1.09 ]
  priors:
    sL_prior_sigma: 0.02
    rbw_prior_sigma_deg: 3.0

wheel_imu_right:
  isuse: false
  file: ""
  pick: norm
  radius: 0.3525
  lever: [ -0.64, -0.628, 2.122 ]
  odoangle: [ 0, -0.30, -1.09 ]
  priors:
    sR_prior_sigma: 0.02
    rbw_prior_sigma_deg: 3.0
