# OB_GINS: Optimization-Based GNSS/INS Integrated Navigation System

# Data files
# GNSS and Truth both use the aligned RTK file
gnssfile: "D:/Code/dataset/0628tuiche/transformed/2Dongxi/20250627-222417-~1_rtk.txt"
outputpath: "D:/Code/dataset/0628tuiche/transformed/output"
save_multi_imu: true

# Multi-IMU configurations

# Main Body IMU (FOG)
imu_main:
  type: "standard"
  file: "D:/Code/dataset/0628tuiche/transformed/2Dongxi/20250627_222419_2_fog_sp.txt"
  columns: 7
  rate_hz: 1000
  antlever: [ 0.0, 0.0, 0.0 ]
  imunoise:
    arw: 0.1 # FOG is higher precision
    vrw: 0.05
    gbstd: 0.1
    abstd: 100
    gsstd: 50
    asstd: 500
    corrtime: 1.0

# # Auxiliary IMU (MEMS)
# center_imu1:
#   type: "standard"
#   file: "D:/Code/dataset/0628tuiche/transformed/2Dongxi/20250627_222419_4_mems_sp.txt"
#   columns: 7
#   rate_hz: 200
#   antlever: [ 0.0, 0.0, 0.0 ] # Assume co-located or small lever arm for now
#   odolever: [ 0,0, 0 ]
#   bodyangle: [ 0, 0, 0 ]
#   imunoise:
#     arw: 1.2 # MEMS noise
#     vrw: 6
#     gbstd: 50
#     abstd: 2000
#     gsstd: 50
#     asstd: 500
#     corrtime: 1.0

# Processing time parameters
windows: 50
starttime: 680
endtime: 1230
aligntime: 5
kf_interval_sec: 0.1

# Iterations
num_iterations: 20

# GNSS outlier culling
is_outlier_culling: false

# consider the Earths rotation
isearth: true

odometer:
    isuseodo: false
    std: [ 0.05, 0.05, 0.05 ]
    srw: 100

# GNSS outage parameters
isuseoutage: false
outagetime: 0
outagelen: 10
outageperiod: 160

# GNSS threshold
gnssthreshold: 20.0

# Debug
debug:
  enable: true
  level: 3

# Comparison script settings
comparison:
  enable: true
  python_script: "d:/Code/OB_GINS_Liu/plot_comparison.py"
  truth_file: "D:/Code/dataset/0628tuiche/transformed/2Dongxi/20250627-222417-~1_rtk.txt"
  label: "OB_GINS"