imufile: "D:/Code/OB_GINS/dataset/ADIS16465.txt"
gnssfile: "D:/Code/OB_GINS/dataset/GNSS_RTK.pos"
outputpath: "D:/Code/OB_GINS/out/liu_30s_no_odo"

windows: 300
starttime: 357473
endtime: 357503   # 30s

num_iterations: 20
is_outlier_culling: false

initvel: [ 0, 0, 0 ]
initatt: [ 0, 0, 276 ]
initgb: [ 0, 0, 0 ]
initab: [ 0, 0, 0 ]

imudatalen: 7
imudatarate: 200
isearth: true

antlever: [ -0.073, 0.302, 0.087 ]
odolever: [ -0.64, -0.628, 2.122 ]
bodyangle: [ 0, -0.30, -1.09 ]

odometer:
  isuseodo: false
  std: [ 0.05, 0.05, 0.05 ]
  srw: 100
  factor:
    sodo_prior_sigma: 0.02
    rbw_prior_sigma_deg: 3.0
    use_nhc: false

odometer_left:
  isuseodo: false
  file: "D:/Code/OB_GINS/dataset/odometer.txt"
  columns: 2
  lever: [ -0.64, -0.628, 2.122 ]
  odoangle: [ 0, -0.30, -1.09 ]
  factor:
    sodo_prior_sigma: 0.02

odometer_right:
  isuseodo: true
  file: "D:/Code/OB_GINS/dataset/odometer.txt"
  columns: 2
  lever: [ -0.64, -0.628, 2.122 ]
  odoangle: [ 0, -0.30, -1.09 ]
  factor:
    sodo_prior_sigma: 0.02

imumodel:
  arw: 0.1
  vrw: 0.1
  gbstd: 25.0
  abstd: 200.0
  corrtime: 1.0

isuseoutage: false
outagetime: 0
outagelen: 0
outageperiod: 0

gnssthreshold: 0.2
